# Generated by Django 2.1.7 on 2024-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
